--- 
- hosts: localhost
  name: Deploy SNOCP
  gather_facts: false
  vars_files:
    - auth.yml
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: ../kubeconfig
  roles:
    - role: snocp
      vars:
        snocp_provider: hetzner
        snocp_tf_state: present
        snocp_cluster_name: "hz"
        snocp_cluster_domain: "msl.cloud"
        snocp_cluster_version: "4.12"
        snocp_cluster_arch: "arm64"
